name: Checks

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - ".github/"
      - "**/Makefile.toml"
      - "release.toml"
      - "LICENSE"
      - "README.md"
  pull_request:
    branches:
      - main
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  # Run cargo clippy -- -D warnings
  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: dsherret/rust-toolchain-file@v1
      - name: Run clippy
        uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
          args: -- -D warnings

  # Run cargo fmt --all -- --check
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: dsherret/rust-toolchain-file@v1
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --all -- --check

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Install Dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev pkg-config
    - name: Build
      run: cargo build --release --all-targets --verbose
    - name: Build zbus
      if: ${{ runner.os == 'Linux' }}
      run: cargo build --release --all-targets --verbose --no-default-features --features=use_zbus
